<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Il2CppStringDump</RootNamespace>
    <AssemblyName>Il2CppStringDump</AssemblyName>

    <BepInExCore>C:\Users\sw\Desktop\SheepClicker\BepInEx\core</BepInExCore>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="LibCpp2IL">
      <HintPath>$(BepInExCore)\LibCpp2IL.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="AssetRipper.Primitives">
      <HintPath>$(BepInExCore)\AssetRipper.Primitives.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>
