"""Engine-independent Git workflow for official game version updates."""

from .git_workflow import (
    ORIGINAL_BRANCH,
    TRANSLATION_BRANCH,
    BootstrapResult,
    GitWorkflowError,
    RepositoryStatus,
    UpdateResult,
    UpdateExternalChange,
    UpdateFileChange,
    UpdateImageChange,
    UpdatePreview,
    abort_update,
    apply_official_update,
    apply_registered_original,
    bootstrap_repository,
    checkout_translation_branch,
    conflict_paths,
    continue_with_official,
    inspect_repository,
    local_branch_names,
    preview_official_update,
    record_version_metadata,
    register_translation_branch,
)

__all__ = [
    "ORIGINAL_BRANCH",
    "TRANSLATION_BRANCH",
    "BootstrapResult",
    "GitWorkflowError",
    "RepositoryStatus",
    "UpdateResult",
    "UpdateExternalChange",
    "UpdateFileChange",
    "UpdateImageChange",
    "UpdatePreview",
    "abort_update",
    "apply_official_update",
    "apply_registered_original",
    "bootstrap_repository",
    "checkout_translation_branch",
    "conflict_paths",
    "continue_with_official",
    "inspect_repository",
    "local_branch_names",
    "preview_official_update",
    "record_version_metadata",
    "register_translation_branch",
]
