"""A scene-jump menu, so testing a fixed line does not need a save.

A TyranoScript save stores two things that make patched text awkward to test.
``data.layer`` is the *rendered HTML* of every layer, restored verbatim by
``setLayerHtml`` on load, so the text on screen right after loading is whatever
was on it when the save was made - one click forward re-renders it from the
patched script. Worse, ``data.current_order_index`` is an integer index into the
parsed element array of the current scenario, and load resumes with
``nextOrderWithIndex``. Dropping or inserting a single ``[r]`` changes how many
elements that file parses to, so a save taken later in the same file resumes at
the wrong element.

Rather than fight that, this sidesteps it: a generated menu that jumps straight
to any label in the game, so a fixed line can be looked at without a save at all.

It is built from the injected output, so the labels are always the ones actually
shipping, and it is written into the same tree - ``inject`` only rewrites the
files it patches, so the generated file survives, and the entry point is spliced
in the same way ``rewrap`` edits the output.

Off by default. ``tl.py inject --debug-menu`` builds it; a release build simply
leaves the flag off and the file is never written.
"""
from __future__ import annotations

import re
from pathlib import Path

from . import codes

MENU_FILE = "data/scenario/_debug.ks"
CONFIG_FILE = "data/system/Config.tjs"

#: where the entry point is spliced in, and what it has to sit after
ENTRIES = (
    ("data/scenario/title.ks", "*start"),
    ("data/scenario/base/base.ks", "*bg_change"),
)

#: three columns, and as many rows as fit above the bottom edge
COLUMNS = (30, 660, 1290)
TOP, STEP, BOTTOM = 120, 42, 1030
SIZE = 21
PER_PAGE = len(COLUMNS) * ((BOTTOM - TOP) // STEP)

LABEL_RE = re.compile(r"^\*([^\s|]+)")


def labels(root: Path) -> list[tuple[str, list[str]]]:
    """``(scenario path, labels)`` for every file that has any, biggest first."""
    out = []
    for path in sorted((root / "data" / "scenario").rglob("*.ks")):
        rel = path.relative_to(root / "data" / "scenario").as_posix()
        if rel.startswith("_"):
            continue
        found = []
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            match = LABEL_RE.match(line.strip())
            if match:
                found.append(match.group(1))
        if found:
            out.append((rel, found))
    return out


def _escape(text: str) -> str:
    """Safe inside a quoted attribute value.

    KAG's ``makeTag`` deletes every literal space it finds inside quotes, so a
    label reading "base/base.ks  (26)" arrives as "base/base.ks(26)". U+00A0
    survives and renders as a space - the same trick the injector uses.
    """
    return (text.replace("\\", "\\\\").replace('"', "'")
                .replace(" ", codes.NBSP))


def _grid(items, render) -> list[str]:
    """Lay ``items`` out down the columns, one page's worth."""
    lines, rows = [], (BOTTOM - TOP) // STEP
    for i, item in enumerate(items):
        x = COLUMNS[i // rows]
        y = TOP + (i % rows) * STEP
        lines.append(render(item, x, y))
    return lines


def build(root: Path) -> int:
    """Write the menu and splice its entry points. Returns the label count."""
    files = labels(root)
    total = sum(len(names) for _, names in files)
    out = [
        ";  Generated by tyranotl/debugmenu.py - not part of the game.",
        ";  Jumps straight to any label so a patched line can be checked",
        ";  without a save. See the module docstring for why saves do not",
        ";  survive a text patch.",
        "",
        "*debug_top",
        "[cm][clearstack][clearfix][fi1][fi2]",
        "[hide_mes]",
        "[freeimage layer=1][freeimage layer=2]",
        f'[ptext layer="1" text="{_escape("Scene jump - debug build")}" '
        f'x="30" y="40" size="30" color="0xffffff"]',
        '[ptext layer="1" text="&\'labels: {0}\'" x="30" y="76" size="20" '
        'color="0xaaaaaa"]'.format(total),
        f'[glink color="skt_mono_03" size="22" '
        f'text="{_escape("Unlock everything (all_clear)")}" '
        f'target="debug_unlock" x="1290" y="40"]',
        f'[glink color="skt_mono_03" size="22" '
        f'text="{_escape("Max Affection and Lewdness")}" '
        f'target="debug_max" x="1290" y="76"]',
    ]
    out += _grid(
        list(enumerate(files)),
        lambda pair, x, y: (
            f'[glink color="skt_mono_03" size="{SIZE}" '
            f'text="{_escape(f"{pair[1][0]}  ({len(pair[1][1])})")}" '
            f'target="debug_f{pair[0]}" x="{x}" y="{y}"]'))
    out += ["[s]", ""]

    out += [
        "*debug_unlock",
        "[all_clear]",
        "[jump target=debug_top]",
        "",
        "*debug_max",
        '[eval exp="f.koko_status[0][1]=99999;f.koko_status[1][1]=99999"]',
        "[jump target=debug_top]",
        "",
    ]

    for index, (rel, names) in enumerate(files):
        for page in range(0, max(1, len(names)), PER_PAGE):
            tag = f"debug_f{index}" if page == 0 else f"debug_f{index}_{page}"
            chunk = names[page:page + PER_PAGE]
            out += [
                f"*{tag}",
                "[cm][clearfix][fi1]",
                "[hide_mes]",
                f'[ptext layer="1" text="{_escape(rel)}" x="30" y="40" '
                f'size="26" color="0xffffff"]',
                '[glink color="skt_mono_03" size="22" text="back" '
                'target="debug_top" x="1290" y="40"]',
            ]
            if page + PER_PAGE < len(names):
                out.append(
                    f'[glink color="skt_mono_03" size="22" text="more" '
                    f'target="debug_f{index}_{page + PER_PAGE}" x="1290" y="76"]')
            out += _grid(
                chunk,
                lambda name, x, y, rel=rel: (
                    f'[glink color="skt_mono_03" size="{SIZE}" '
                    f'text="{_escape(name)}" storage="{rel}" '
                    f'target="{_escape(name)}" x="{x}" y="{y}"]'))
            out += ["[s]", ""]

    target = root / MENU_FILE
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(out) + "\n", encoding="utf-8")
    _splice_entries(root)
    _debug_config(root)
    return total


def _debug_config(root: Path, app_root: Path | None = None) -> None:
    """Turn the engine's error display on for the debug build.

    ``debugMenu.visible`` adds no menu - it makes ``kag.error`` print the
    scenario and line of whatever went wrong, which is what you want when
    jumping into a scene that expects state it has not been given.
    """
    app_root = app_root or root.parent / "extracted" / "app"
    source = app_root / CONFIG_FILE
    if not source.exists():
        return
    text = source.read_text(encoding="utf-8", errors="replace")
    text = text.replace(";debugMenu.visible=false", ";debugMenu.visible=true", 1)
    target = root / CONFIG_FILE
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding="utf-8")


def _splice_entries(root: Path) -> None:
    """Put a way in on the title screen and the home screen."""
    link = ('[glink color="skt_mono_03" size="20" text="scene jump" '
            'storage="_debug.ks" target="debug_top" x="30" y="30"]')
    for rel, after in ENTRIES:
        path = root / rel
        if not path.exists():
            continue
        lines = path.read_text(encoding="utf-8", errors="replace").split("\n")
        if any("_debug.ks" in line for line in lines):
            continue
        for i, line in enumerate(lines):
            if line.strip().split("|")[0].strip() == after:
                lines.insert(i + 1, link)
                break
        else:
            continue
        path.write_text("\n".join(lines), encoding="utf-8", newline="")
