// Pins the Node, Python and Windows Git downloads that setup installs, for the
// versions in .node-version, .python-version and .mingit-version. Run it after
// changing any of them.
import fs from "node:fs";
import path from "node:path";
import { root, platforms } from "./dependencies.mjs";

const version = (file) => fs.readFileSync(path.join(root, file), "utf8").trim();
async function get(url) {
  const response = await fetch(url, { headers: { "User-Agent": "DazedTL" } });
  if (!response.ok) throw new Error(`${url} answered ${response.status}.`);
  return response;
}
async function checksums(url) {
  const body = await (await get(url)).text();
  return new Map(
    body
      .trim()
      .split("\n")
      .map((line) => line.trim().split(/\s+/).reverse()),
  );
}

const node = version(".node-version");
const python = version(".python-version");
const mingit = version(".mingit-version");
const builds = "https://github.com/astral-sh/python-build-standalone";
const asset = (tag, triple) =>
  `cpython-${python}+${tag}-${triple}-install_only_stripped.tar.gz`;
// Releases are newest first; take the newest that builds every platform. Each
// lists hundreds of files, so small pages keep the API from timing out.
let release;
for (let page = 1; !release && page <= 5; page++) {
  /** @type {{ tag_name: string, assets: { name: string }[] }[]} */
  const releases = await (
    await get(
      `https://api.github.com/repos/astral-sh/python-build-standalone/releases?per_page=5&page=${page}`,
    )
  ).json();
  release = releases.find((item) =>
    Object.values(platforms).every((target) =>
      item.assets.some(
        (file) => file.name === asset(item.tag_name, target.python),
      ),
    ),
  );
}
if (!release)
  throw new Error(`No recent Python build has ${python} for every platform.`);
const nodeSums = await checksums(
  `https://nodejs.org/dist/v${node}/SHASUMS256.txt`,
);
const pythonSums = await checksums(
  `${builds}/releases/download/${release.tag_name}/SHA256SUMS`,
);
const lines = [];
for (const target of Object.values(platforms)) {
  const nodeFile = `node-v${node}-${target.node}`;
  const pythonFile = asset(release.tag_name, target.python);
  for (const { sums, file, url } of [
    {
      sums: nodeSums,
      file: nodeFile,
      url: `https://nodejs.org/dist/v${node}/${nodeFile}`,
    },
    {
      sums: pythonSums,
      file: pythonFile,
      url: `${builds}/releases/download/${release.tag_name}/${pythonFile}`,
    },
  ]) {
    const hash = sums.get(file);
    if (!hash) throw new Error(`No published checksum for ${file}.`);
    lines.push(`${hash}  ${url}`);
  }
}
// Git for Windows lists each file's SHA-256 in its release notes; GitHub's own
// digest of the uploaded file must agree.
/** @type {{ body: string, assets: { name: string, digest?: string, browser_download_url: string }[] }} */
const git = await (
  await get(
    `https://api.github.com/repos/git-for-windows/git/releases/tags/v${mingit}`,
  )
).json();
const gitFile = git.assets.find((file) =>
  /^MinGit-[\d.]+-64-bit\.zip$/.test(file.name),
);
const gitHash =
  gitFile &&
  new RegExp(
    `${gitFile.name.replaceAll(".", "\\.")}\\s*\\|\\s*([0-9a-f]{64})`,
  ).exec(git.body)?.[1];
if (!gitFile || !gitHash || gitFile.digest !== `sha256:${gitHash}`)
  throw new Error(`Git for Windows ${mingit} has no verifiable 64-bit MinGit.`);
lines.push(`${gitHash}  ${gitFile.browser_download_url}`);
fs.writeFileSync(
  path.join(root, "scripts/runtimes.lock"),
  "# Generated by scripts/runtimes.mjs from .node-version, .python-version and .mingit-version.\n" +
    lines.join("\n") +
    "\n",
);
console.log(
  `Pinned Node ${node}, Python ${python} (${release.tag_name}) and Git for Windows ${mingit}.`,
);
