// Pins the Node and Python downloads that setup installs, for the versions in
// .node-version and .python-version. Run it after changing either file.
import fs from "node:fs";
import path from "node:path";
import { root, platforms } from "./dependencies.mjs";

const version = (file) => fs.readFileSync(path.join(root, file), "utf8").trim();
async function get(url) {
  const response = await fetch(url, { headers: { "User-Agent": "DazedTL" } });
  if (!response.ok) throw new Error(`${url} answered ${response.status}.`);
  return response;
}
async function checksums(url) {
  const body = await (await get(url)).text();
  return new Map(
    body
      .trim()
      .split("\n")
      .map((line) => line.trim().split(/\s+/).reverse()),
  );
}

const node = version(".node-version");
const python = version(".python-version");
const builds = "https://github.com/astral-sh/python-build-standalone";
const asset = (tag, triple) =>
  `cpython-${python}+${tag}-${triple}-install_only_stripped.tar.gz`;
// Releases are newest first; take the newest that builds every platform. Each
// lists hundreds of files, so small pages keep the API from timing out.
let release;
for (let page = 1; !release && page <= 5; page++) {
  /** @type {{ tag_name: string, assets: { name: string }[] }[]} */
  const releases = await (
    await get(
      `https://api.github.com/repos/astral-sh/python-build-standalone/releases?per_page=5&page=${page}`,
    )
  ).json();
  release = releases.find((item) =>
    Object.values(platforms).every((target) =>
      item.assets.some(
        (file) => file.name === asset(item.tag_name, target.python),
      ),
    ),
  );
}
if (!release)
  throw new Error(`No recent Python build has ${python} for every platform.`);
const nodeSums = await checksums(
  `https://nodejs.org/dist/v${node}/SHASUMS256.txt`,
);
const pythonSums = await checksums(
  `${builds}/releases/download/${release.tag_name}/SHA256SUMS`,
);
const lines = [];
for (const target of Object.values(platforms)) {
  const nodeFile = `node-v${node}-${target.node}`;
  const pythonFile = asset(release.tag_name, target.python);
  for (const { sums, file, url } of [
    {
      sums: nodeSums,
      file: nodeFile,
      url: `https://nodejs.org/dist/v${node}/${nodeFile}`,
    },
    {
      sums: pythonSums,
      file: pythonFile,
      url: `${builds}/releases/download/${release.tag_name}/${pythonFile}`,
    },
  ]) {
    const hash = sums.get(file);
    if (!hash) throw new Error(`No published checksum for ${file}.`);
    lines.push(`${hash}  ${url}`);
  }
}
fs.writeFileSync(
  path.join(root, "scripts/runtimes.lock"),
  "# Generated by scripts/runtimes.mjs from .node-version and .python-version.\n" +
    lines.join("\n") +
    "\n",
);
console.log(`Pinned Node ${node} and Python ${python} (${release.tag_name}).`);
